spring:
  application:
    name: products
  datasource:
    url: jdbc:postgresql://localhost:5555/ecommerce_products
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    fail-on-missing-locations: true

server:
  port: 8081